// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/swaingotnochill/tempmee/domain"
)

// BookUseCase is an autogenerated mock type for the BookUseCase type
type BookUseCase struct {
	mock.Mock
}

// DeleteBook provides a mock function with given fields: c, id
func (_m *BookUseCase) DeleteBook(c context.Context, id string) error {
	ret := _m.Called(c, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBooks provides a mock function with given fields: c
func (_m *BookUseCase) GetBooks(c context.Context) ([]*domain.Book, error) {
	ret := _m.Called(c)

	var r0 []*domain.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Book, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Book); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBooksByID provides a mock function with given fields: c, id
func (_m *BookUseCase) GetBooksByID(c context.Context, id string) (*domain.Book, error) {
	ret := _m.Called(c, id)

	var r0 *domain.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Book, error)); ok {
		return rf(c, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Book); ok {
		r0 = rf(c, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveBook provides a mock function with given fields: c, book
func (_m *BookUseCase) SaveBook(c context.Context, book *domain.Book) error {
	ret := _m.Called(c, book)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Book) error); ok {
		r0 = rf(c, book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBookUseCase creates a new instance of BookUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookUseCase {
	mock := &BookUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
